# Generated by Django 4.1.2 on 2022-11-12 01:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='potluck',
            name='host',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='potluck',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='potluck',
            name='name',
            field=models.CharField(max_length=64),
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(blank=True, max_length=64, null=True)),
                ('potluck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.potluck')),
            ],
        ),
    ]
