# Generated by Django 4.1.2 on 2022-11-12 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_potluck_host_alter_potluck_date_alter_potluck_name_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Items',
            new_name='Item',
        ),
    ]
