# Generated by Django 4.1.2 on 2022-11-12 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_rename_items_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='contributor',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
