# Generated by Django 4.1.2 on 2022-11-12 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_item_contributor'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='contributor_email',
            field=models.EmailField(blank=True, max_length=64, null=True),
        ),
    ]
